/* DROPS TABLES */
DROP TABLE IF EXISTS PRESUPUESTO;
DROP TABLE IF EXISTS CONTACTO;
DROP TABLE IF EXISTS CLIENTE;

/* CREATE TABLES */
CREATE TABLE CLIENTE(
	ID 				SERIAL 			NOT NULL,
	CALLE			VARCHAR(50),
	NUMERO			INT,
	ESQUINA			VARCHAR(50),
	EMAIL			VARCHAR(50),
	BAJA			BOOLEAN			DEFAULT 0,
	PRIMARY KEY		(ID),
	UNIQUE			(EMAIL)
);

CREATE TABLE CONTACTO(
	ID 				SERIAL 			NOT NULL,
	IDCLIENTE		BIGINT(20)		UNSIGNED NOT NULL,
	NOMBRE			VARCHAR(50),
	APELLIDO		VARCHAR(50),
	TELEFONO		VARCHAR(20),
	NOTA			TEXT,
	BAJA			BOOLEAN			DEFAULT 0,
	PRIMARY KEY		(ID),
	UNIQUE			(TELEFONO),
	INDEX			(TELEFONO)
);

CREATE TABLE PRESUPUESTO(
	ID 				SERIAL 			NOT NULL,
	IDCLIENTE		BIGINT(20)		UNSIGNED NOT NULL,
	TITULO			VARCHAR(50),
	RESUMEN			TEXT,
	PDF				VARCHAR(50),
	FECHA			DATETIME,
	PRECIO			INT,
	ESTADO			VARCHAR(50),
	PINTURACODIGO	VARCHAR(10),
	PINTURALITROS	VARCHAR(10),
	PINTURATIPO		VARCHAR(50),
	BAJA			BOOLEAN			DEFAULT 0,
	PRIMARY KEY		(ID),
	UNIQUE			(PDF)
);